Add deploy trigger

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -8,6 +8,8 @@ on:
   pull_request:
     branches:
       - main
+  repository_dispatch:
+    types: [deploy]
 
 env:
   RUST_BACKEND_IMAGE: writhkin/rust-backend:latest
@@ -15,8 +17,8 @@ env:
   DOCKER_COMPOSE_PATH: pipelines/docker-compose.yml
 
 jobs:
-  build-and-test:
-    name: Build and Test
+  build-and-deploy:
+    name: Build and Deploy
     runs-on: ubuntu-latest
 
     steps:
@@ -46,7 +48,9 @@ jobs:
           context: backend/rust
           file: backend/rust/Dockerfile
           push: true
-          tags: ${{ env.RUST_BACKEND_IMAGE }}
+          tags: |
+            writhkin/rust-backend:latest
+            writhkin/rust-backend:${{ github.sha }}
 
       - name: Deploy with Docker Compose
         run: |
@@ -55,5 +59,14 @@ jobs:
         env:
           DATABASE_URL: postgres://bd:Bobbydole1%40%21@db:5432/trustystack
 
-  # Add additional jobs for deployment, if necessary
+      - name: Trigger Render Deployment
+        if: success()
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}")
+          if [ "$response" -eq 200 ]; then
+            echo "Render deployment triggered successfully."
+          else
+            echo "Failed to trigger Render deployment. Response code: $response"
+            exit 1
+          fi
 
